import Link from "next/link";

const steps = [
  ["01", "Read the heat", "Connect a supported zone to live FortyGuard evidence with a durable activity record."],
  ["02", "Build the case", "Retrieve cited intervention evidence and keep source provenance beside every recommendation."],
  ["03", "Govern the decision", "Run deterministic portfolio optimization, then route the result through manager approval."],
];

export default function Home() {
  return <main className="landing-shell">
    <nav className="landing-nav"><Link href="/" className="landing-brand"><span className="brand-mark">✦</span> CoolProof <span className="brand-beta">OPS</span></Link><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#boundaries">Trust boundary</a><Link href="/login" className="button ghost">Sign in</Link></div></nav>
    <section className="landing-hero"><div className="landing-copy"><div className="landing-eyebrow">A DECISION SYSTEM FOR HOTTER CITIES</div><h1>See where heat hurts. Fund what works.</h1><p className="landing-lede">CoolProof turns satellite heat evidence into a traceable cooling portfolio—so climate teams can move from a map, to a budget, to a measured result without losing the thread.</p><div className="landing-actions"><Link href="/login" className="button primary">Enter the workspace <span aria-hidden="true">↗</span></Link><a href="#how-it-works" className="button ghost">See the method</a></div><div className="landing-proof"><span className="proof-dot" /> Live provider evidence · deterministic allocation · human approval</div></div><div className="landing-observation" aria-label="Example live heat observation"><div className="observation-top"><span><i className="signal-live" /> LIVE SIGNAL</span><span>PHX / 100M GRID</span></div><div className="observation-map"><span className="map-scan" /><span className="map-point point-a" /><span className="map-point point-b" /><span className="map-point point-c" /><span className="map-route route-a" /><span className="map-route route-b" /><div className="map-label label-a">41.8°</div><div className="map-label label-b">38.6°</div></div><div className="observation-bottom"><div><small>EXPOSURE INDEX</small><strong>8.4 <em>/ 10</em></strong></div><div><small>DATA SOURCE</small><strong>FortyGuard</strong></div><div><small>UPDATED</small><strong>Now</strong></div></div></div></section>
    <section className="landing-signal"><div><span className="eyebrow">THE PROMISE</span><h2>One chain of custody from temperature to intervention.</h2></div><p>Every recommendation keeps its source, calculation boundary, uncertainty, and approval state visible to the people accountable for the decision.</p></section>
    <section id="how-it-works" className="landing-section"><div className="eyebrow">HOW IT WORKS</div><h2>From a hot block to a defensible plan.</h2><div className="landing-steps">{steps.map(([number, title, copy]) => <article className="landing-step" key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{copy}</p><span className="step-line" /></article>)}</div></section>
    <section id="boundaries" className="landing-section landing-boundary"><div><div className="eyebrow">TRUST BOUNDARY</div><h2>The UI shows the work. AWS owns the facts.</h2></div><div className="boundary-list"><div><strong>FortyGuard</strong><span>Provider heat evidence and activity state</span></div><div><strong>PostgreSQL + pgvector</strong><span>Tenant-isolated sources and citations</span></div><div><strong>OR-Tools</strong><span>Budget, equity, capacity, and uncertainty constraints</span></div><div><strong>LangGraph</strong><span>Checkpointed four-agent workflow with approval gates</span></div></div></section>
    <footer className="landing-footer"><span>CoolProof · Aurorium Nexus Cooling</span><span>Built for auditable urban-cooling decisions.</span></footer>
  </main>;
}
