import Link from "next/link";

const steps = [
  ["01", "Find the pressure points", "See which neighborhoods carry the greatest heat exposure and where action can make a difference."],
  ["02", "Compare the choices", "Bring cost, equity, feasibility, and evidence into the same decision—not another spreadsheet."],
  ["03", "Show what changed", "Keep approval, implementation, and measured outcomes connected after the funding decision."],
];

export default function Home() {
  return <main className="landing-shell">
    <nav className="landing-nav"><Link href="/" className="landing-brand"><span className="brand-mark">✦</span> CoolProof <span className="brand-beta">OPS</span></Link><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#boundaries">Trust boundary</a><Link href="/login" className="button ghost">Sign in</Link></div></nav>
    <section className="landing-hero"><div className="landing-copy"><div className="landing-eyebrow">COOLPROOF FOR CITY CLIMATE TEAMS</div><h1>Make the next cooling decision easier to defend.</h1><p className="landing-lede">CoolProof helps teams move from neighborhood heat to a funded, measurable action plan—with the evidence and reasoning still attached when the meeting is over.</p><div className="landing-actions"><Link href="/login" className="button primary">Explore the workspace <span aria-hidden="true">↗</span></Link><a href="#how-it-works" className="button ghost">How teams use it</a></div><div className="landing-proof"><span className="proof-dot" /> Built for climate, capital, and community decisions</div></div><div className="landing-observation" aria-label="Example neighborhood heat view"><div className="observation-top"><span><i className="signal-live" /> NEIGHBORHOOD VIEW</span><span>PHOENIX / CENTRAL</span></div><div className="observation-map"><span className="map-scan" /><span className="map-point point-a" /><span className="map-point point-b" /><span className="map-point point-c" /><span className="map-route route-a" /><span className="map-route route-b" /><div className="map-label label-a">41.8°</div><div className="map-label label-b">38.6°</div><div className="map-caption">Heat exposure is concentrated along the school corridor.</div></div><div className="observation-bottom"><div><small>PRIORITY AREA</small><strong>School corridor</strong></div><div><small>DECISION STATUS</small><strong>Ready to compare</strong></div></div></div></section>
    <section className="landing-signal"><div><span className="eyebrow">WHY COOLPROOF</span><h2>Less time reconciling evidence. More time deciding what to do.</h2></div><p>Bring the heat signal, intervention options, budget constraints, and expected outcomes into one shared view your team can review together.</p></section>
    <section id="how-it-works" className="landing-section"><div className="eyebrow">HOW TEAMS USE IT</div><h2>From a hot block to a plan people can stand behind.</h2><div className="landing-steps">{steps.map(([number, title, copy]) => <article className="landing-step" key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{copy}</p><span className="step-line" /></article>)}</div></section>
    <section id="boundaries" className="landing-section landing-boundary"><div><div className="eyebrow">BUILT FOR TRUST</div><h2>Clear enough for a working session. Rigorous enough for the record.</h2><p className="landing-boundary-copy">Recommendations remain explainable, calculations remain deterministic, and approval remains with the people responsible for the investment.</p></div><div className="boundary-list"><div><strong>Evidence stays attached</strong><span>Sources and citations follow the recommendation.</span></div><div><strong>Constraints stay visible</strong><span>Budget, equity, capacity, and uncertainty are not hidden.</span></div><div><strong>Outcomes stay measurable</strong><span>Expected and observed results can be compared later.</span></div></div></section>
    <footer className="landing-footer"><span>CoolProof</span><span>Cooling decisions with a clear chain of evidence.</span><Link href="/login">Enter the workspace ↗</Link></footer>
  </main>;
}
